# src/comparative/configs/train/cpu_ddp.yaml
_target_: pytorch_lightning.Trainer

accelerator: cpu
devices: 12                    # One per physical core (matches your CPU)
strategy: ddp                    # True multi-process DDP
max_epochs: 5
log_every_n_steps: 20
default_root_dir: /data_vault/COmparative_Study_of_Multimodal_Represenations/src/comparative/checkpoints/
