# src/comparative/configs/model/classical_late.yaml
_target_: comparative.models.classical.late_fusion.LateFusionClassifier
text_model_name: distilbert-base-uncased
image_model_name: resnet18
n_classes: 139
use_text: true
use_image: false
use_graph: false
use_tabular: false
image_emb_dim: 512
fusion_hidden: 256
lr: 2.0e-5
wd: 0.01
