# src/comparative/configs/config.yaml
defaults:
  - data: amazon       # Can be: amazon, fashionai, movielens
  - model: classical_early   # Can be: classical_early, classical_late, clip, vilbert, mvae, hybrid
  - train: cpu         # Or: cpu_debug, gpu, cpu_ddp
  - hardware: hardware
  - override hydra/job_logging: disabled
  - _self_

# Global seed for reproducibility
seed: 42

# Directory for saving checkpoints/results/logs
output_dir: ${oc.env:PROJECT_ROOT}/results/${data}
